services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: kq-remote-link-hbbs
    command: hbbs -r ${KQ_RELAY_SERVER:-43.154.197.96:21117} -k ${KQ_SERVER_KEY:-_}
    volumes:
      - ./data:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: kq-remote-link-hbbr
    command: hbbr -k ${KQ_SERVER_KEY:-_}
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
